import { defaultTheme } from "@vuepress/theme-default";

export default {
  theme: defaultTheme({
    logo: "/images/icons/logo.png",
    navbar: [
      // NavbarItem
      {
        text: "POS",
        link: "/pos/",
      },
    ],
    repo: "moumirrai/nestling",
    sidebar: [
      // SidebarItem
      {
        text: "Pozemní stavitelství",
        link: "/pos/",
        children: [
            "/pos/1/",
            "/pos/2/",
            "/pos/3/",
            "/pos/4/",
            "/pos/5/",
            "/pos/6/",
            "/pos/7/",       
            "/pos/8/",
            "/pos/9/",
            "/pos/10/",
            "/pos/11/",
            "/pos/12/",
            "/pos/13/",
            "/pos/14/",
            "/pos/15/",
            "/pos/16/",
            "/pos/17/",
            "/pos/18/",
            "/pos/19/",
            "/pos/20/",
            "/pos/21/",
            "/pos/22/",
            "/pos/23/",
            "/pos/24/",
            "/pos/25/",
            "/pos/26/",
            "/pos/27/",
            "/pos/28/",
            "/pos/29/",
            "/pos/30/",
            "/pos/31/",
            "/pos/32/",
            "/pos/33/",
            "/pos/34/",
            "/pos/35/",
            "/pos/36/",
            "/pos/37/",
            "/pos/38/",
            "/pos/39/",
            "/pos/40/",
            "/pos/41/",
            "/pos/42/",
            "/pos/43/",
            "/pos/44/",
          ],
      },
    ],
    editLinkText: "Upravit tuto stránku",
    lastUpdatedText: "Naposledy upraveno",
    notFound: ["Tato stránka neexistuje"],
    backToHome: "Zpět na úvodní stránku",
    themePlugins: {
        mediumZoom: false,
    },
  }),
};
